export const BACKEND_URI = process.env.NEXT_PUBLIC_BACKEND_API_URL 

export const TURTLE_BACKEND_URI = process.env.NEXT_PUBLIC_TURTLE_API_URL 

export const AZURE_TRANSLATOR_KEY_URI = process.env.AZURE_TRANSLATOR_KEY

export const AZURE_TRANSLATOR_ENDPOINT_URI = process.env.AZURE_TRANSLATOR_ENDPOINT

export const AZURE_TRANSLATOR_LOCATION_URI = process.env.AZURE_TRANSLATOR_LOCATION

export const MONGO_CONNECTION_STRING_URI = process.env.MONGO_CONNECTION_STRING

export const JWT_SECRET = process.env.JWT_SECRET

